-- YUANDI ERP - RLS 비활성화 스크립트
-- 개발 환경에서 테스트를 위해 RLS를 비활성화합니다.
-- 프로덕션에서는 적절한 RLS 정책을 설정해야 합니다.

-- 1. 모든 테이블의 RLS 비활성화
ALTER TABLE IF EXISTS product_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shipments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shipment_tracking_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cashbook_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS system_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS exchange_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS system_health_logs DISABLE ROW LEVEL SECURITY;

-- 2. 확인 메시지
DO $$
BEGIN
    RAISE NOTICE 'RLS가 모든 테이블에서 비활성화되었습니다.';
    RAISE NOTICE '프로덕션 환경에서는 적절한 RLS 정책을 설정하세요!';
END $$;